replicas: 2

adminUser: admin

persistence:
  enabled: true
  size: 10Gi

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi