apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app-key-vault
  namespace: platform-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: platform-app-key-vault

  template:
    metadata:
      labels:
        app: platform-app-key-vault
        azure.workload.identity/use: "true"

    spec:
      serviceAccountName: platform-app-key-vault

      containers:
        - name: platform-app
          image: nginx:1.27-alpine

          volumeMounts:
            - name: runtime-secrets
              mountPath: /mnt/secrets-store
              readOnly: true

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

      volumes:
        - name: runtime-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true

            volumeAttributes:
              secretProviderClass: platform-app-key-vault