apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-app-key-vault
  namespace: platform-app
  annotations:
    azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false